---
version: "3.9"
name: aryon
services:

  aryon:
    container_name: aryon
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
    restart: unless-stopped
